/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hellogradle;

public class App {

    public static void main(String[] args) {
        App r = new App();
		System.out.println("hellogradle");
    }
}
